title: Hao's page
author: Hao Liu

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this

# Build settings
remote_theme: samarsault/plainwhite-jekyll

show_excerpts: true

plainwhite:
  name: Hao LIU - 劉豪
  tagline: Machine Learning Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # path the image to display
  html_lang: "en" # set the lang attribute of the <html> tag for the pages.
  disqus_shortname: blogger
  navigation:
    - title: Blog Posts
      url: "/posts"
  condensed_mobile:
    - home
    - post
    - page
  # generate social links in footer
  social_links:
    github:  HaoLIU94
    linkedIn: in/hao-l-7a4078159/
    email: liuhaoxdu@gmail.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

